# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          python3 -m pip install flake8
          python3 -m flake8 . --max-line-length=127
      - name: Test install
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U .
